version: '3.5'

services:
  test:
    image: elixir:1.9-alpine
    command: mix do local.hex --force, local.rebar --force, deps.get, test, credo --strict
    environment:
      - MIX_ENV=test
    working_dir: /app
    volumes:
      - .:/app
      - "build:/app/_build"
      - "deps:/app/deps"
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5438
    networks:
      default:
        aliases:
          - message-broker-db

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "5602:5672"
      - "15602:15672"
    networks:
      default:
        aliases:
          - message-broker-rabbitmq

volumes:
  build:
  deps:

networks:
  default:
    external:
      name: message-broker
